language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script: yarn start 
deploy:
  - provider: script 
    script: now --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true