language: node_js
node_js:
  - "node"

deploy:
  - provider: script 
    script: now --public --token $NOW_TOKEN -e REACT_APP_SECRET_CODE=$REACT_APP_SECRET_CODE && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
      branch: "refactor/flow"