language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script: yarn build
deploy:
  - provider: script 
    script: now --public --token $NOW_TOKEN -e REACT_APP_SECRET_CODE=$REACT_APP_SECRET_CODE
    skip_cleanup: true
    on:
      master: true
      branch: "refactor/flow"