language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script: yarn test 
before_deploy: npm install now --no-save 
deploy:
  - provider: script 
    script: now --public --token $NOW_TOKEN -e REACT_APP_SECRET_CODE=$REACT_APP_SECRET_CODE
    skip_cleanup: true
    on:
      master: true
      all_branches: true